# H2
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true
